version: "3.7"

services:

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: geekbot_exam
      MYSQL_DATABASE: geekbot_exam
      MYSQL_USER: geekbot_exam
      MYSQL_PASSWORD: geekbot_exam
    ports:
      - "3306:3306"

  traefik:
    restart: always
    image: traefik:v1.7.16
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml

  backend:
    restart: always
    build:
      context: ./backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: geekbot_exam
      MYSQL_USER: geekbot_exam
      MYSQL_PASSWORD: geekbot_exam
    volumes:
      - ./backend/app:/app/app
      - ./backend/public:/app/public
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    labels:
      - "traefik.enable=true"
      - "traefik.backend=backend"
      - "traefik.frontend.rule=Host:exam.geekbot.com;PathPrefix:/api"
      - "traefik.port=3000"
      
  frontend:
    restart: always
    stdin_open: true
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    labels:
      - "traefik.enable=true"
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=Host:exam.geekbot.com"
      - "traefik.port=3000"

volumes:
  mysql_data:
